name: Release to Maven Central

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_USERNAME: ${{ secrets.GPR_USERNAME }}
      GITHUB_PACKAGES_TOKEN: ${{ secrets.GPR_TOKEN }}
      GPG_KEY: ${{ secrets.GPG_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    steps:
      - uses: actions/checkout@v4

      - name: Install toml-cli
        run: pip install toml-cli

      - name: Extract Java version
        id: java_version
        run: |
          JAVA_VERSION=$(toml get versions.java --toml-path gradle/libs.versions.toml | tr -d '"')
          echo "java=$JAVA_VERSION" >> $GITHUB_OUTPUT

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ steps.java_version.outputs.java }}
          distribution: temurin

      - name: Build staging repo
        run: ./gradlew clean publish --stacktrace

      - name: Create bundle
        run: |
          cd build/staging-repo
          zip -r ../bundle.zip .

      - name: Upload bundle to Sonatype Central
        run: |
          BEARER=$(echo -n "${{ secrets.SONATYPE_USERNAME }}:${{ secrets.SONATYPE_PASSWORD }}" | base64)
          curl --fail --request POST \
            --header "Authorization: Bearer $BEARER" \
            --form bundle=@build/bundle.zip \
            "https://central.sonatype.com/api/v1/publisher/upload?publishingType=AUTOMATIC"
